# Generated by Django 5.0.1 on 2024-02-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_user_alter_todo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Todo 완료 여부'),
        ),
        migrations.AddField(
            model_name='todo',
            name='important',
            field=models.BooleanField(default=False, verbose_name='Todo 중요 여부'),
        ),
    ]
