# Generated by Django 5.0.1 on 2024-02-07 06:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_rename_created_post_created_at_alter_post_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="update_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="수정일시",
            ),
            preserve_default=False,
        ),
    ]
